---
- name: install gui packages
  become: yes
  with_items: "{{ gui_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: configure slim
  become: yes
  template:
    src: slim.conf.j2
    dest: /etc/slim.conf

- name: install gui testing packages
  become: yes
  with_items: "{{ gui_testing_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: "testing"
    state: latest
