---
- name: configure communication sources
  become: yes
  template:
    src: "roles/communication/templates/weechat.list.j2"
    dest: "/etc/apt/sources.list.d/weechat.list"
    owner: root
    group: root

- name: ensure communication gpg keys are in place
  become: yes
  apt_key:
    keyserver: "pool.sks-keyservers.net"
    id: "11E9DE8848F2B65222AA75B8D1820DB22A11534E"

- name: configure tox sources
  become: yes
  template:
    src: "roles/communication/templates/tox.list.j2"
    dest: "/etc/apt/sources.list.d/tox.list"
    owner: root
    group: root

- name: ensure tox gpg keys are in place
  become: yes
  apt_key:
    url: "https://pkg.tox.chat/debian/pkg.gpg.key"
