---
- name: install audio packages
  become: yes
  with_items: "{{ audio_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install audio kxstudio trusty packages
  become: yes
  with_items: "{{ audio_kxstudio_trusty_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: trusty
    state: latest

- name: install audio kxstudio lucid packages
  become: yes
  with_items: "{{ audio_kxstudio_lucid_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: lucid
    state: latest

- name: set realtime priority
  become: yes
  template:
    src: audio-limits.conf.j2
    dest: /etc/security/limits.d/audio.conf

- name: setup udev rtc
  become: yes
  template:
    src: 99-rtc.rules.j2
    dest: /etc/udev/rules.d/99-rtc.rules

- name: setup rtc frequency
  become: yes
  lineinfile:
    dest: /etc/rc.local
    insertbefore: "^exit 0"
    regexp: "^echo 3072"
    line: "echo 3072 >/sys/class/rtc/rtc0/max_user_freq"
