---
- name: install network packages
  become: yes
  with_items: "{{ network_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install network syncthing packages
  become: yes
  with_items: "{{ network_syncthing_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: syncthing
    state: latest

- name: configure network manager
  become: yes
  template:
    src: NetworkManager.conf.j2
    dest: /etc/NetworkManager/NetworkManager.conf
  notify:
    - restart network manager
