---
- name: update apt
  become: yes
  apt:
    update_cache: yes

- name: upgrade packages
  become: yes
  apt:
    upgrade: full

- name: install common packages
  become: yes
  with_items: "{{ common_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install common backports packages
  become: yes
  with_items: "{{ common_backports_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: "jessie-backports"
    state: latest

- name: set timezone
  become: yes
  template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify:
    - update timezone
