---
- name: install communication packages
  become: yes
  with_items: "{{ communication_packages }}"
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install communication jessie packages
  become: yes
  with_items: "{{ communication_jessie_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: jessie
    state: latest

- name: install communication nightly packages
  become: yes
  with_items: "{{ communication_nightly_packages }}"
  apt:
    pkg: "{{ item.name }}"
    default_release: nightly
    state: latest

- name: install communication url packages
  become: yes
  with_items: "{{ communication_url_packages }}"
  apt:
    deb: "{{ item.url }}"

- name: install ca certs
  become: yes
  with_items: "{{ communication_certs }}"
  get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/share/ca-certificates/{{ item.filename }}"
    mode: 0644

- name: update certificates
  become: yes
  shell: update-ca-certificates
