- name: configure sources.list
  sudo: yes
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root

- name: configure sources
  sudo: yes
  with_items: "{{ common_sources_list }}"
  template:
    src: "{{ item.name }}.list.j2"
    dest: /etc/apt/sources.list.d/{{ item.name }}.list
    owner: root
    group: root

- name: add keys
  sudo: yes
  with_items: "{{ common_sources_list }}"
  apt_key:
    url: "{{ item.key_url }}"
    state: present

- name: download kxstudio-repos
  sudo: yes
  get_url:
    url: https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_9.2.1~kxstudio1_all.deb
    dest: /root/kxstudio-repos.deb
    sha256sum: 424336af10f4668dc8c1b11a76ffe40175294ccb25b1a6923aa6d2fa0ce9a65c

- name: install kxstudio-repos
  sudo: yes
  apt:
    deb: /root/kxstudio-repos.deb

- name: update apt
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: make everything ok
  sudo: yes
  command: apt-get install -fy --force-yes

- name: install packages
  sudo: yes
  with_items: pretask_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
