- name: configure sources.list
  sudo: yes
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root

- name: add syncthing key
  sudo: yes
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: add syncthing repo
  sudo: yes
  template:
    src: syncthing.list.j2
    dest: /etc/apt/sources.list.d/syncthing.list
    owner: root
    group: root

- name: download kxstudio-repos
  sudo: yes
  get_url:
    url: https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_8.2.1~kxstudio1_all.deb
    dest: /root/kxstudio-repos.deb
    sha256sum: 739336d1e621c7e6553f0c46baabefeafa5eb75af126c104826e02252f20db55

- name: install kxstudio-repos
  sudo: yes
  apt:
    deb: /root/kxstudio-repos.deb

- name: update apt
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: make everything ok
  sudo: yes
  command: apt-get install -fy --force-yes

- name: install packages
  sudo: yes
  with_items: pretask_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
