- name: configure sources.list
  sudo: yes
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root

- name: add syncthing key
  sudo: yes
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: add syncthing repo
  sudo: yes
  template:
    src: syncthing.list.j2
    dest: /etc/apt/sources.list.d/syncthing.list
    owner: root
    group: root

- name: update apt
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: make everything ok
  sudo: yes
  command: apt-get install -fy --force-yes

- name: install packages
  sudo: yes
  with_items: pretask_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
