---
- name: configure audio sources
  become: yes
  template:
    src: "roles/audio/templates/kxstudio.list.j2"
    dest: "/etc/apt/sources.list.d/kxstudio.list"
    owner: root
    group: root

- name: ensure audio gpg keys are in place
  become: yes
  with_items: "{{ audio_gpg_keys }}"
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "{{ item.key }}"
